### ISSUE TITLE
Compile on Arch X86_64 on Ubuntu 18.04

### ISSUE THREAD

**Issue by sebastianene07** [raspberrypi/quake3#12]
I'm trying to build from master HEAD: 8d89a2a3c1707bf0f75b2ea26645b872e97c0b95
with this Makefile.local options:

```
COMPILE_PLATFORM=linux
COMPILE_ARCH=x86_64
COPYDIR=~/.q3/
CC=gcc
```

Running : make -f Makefile_ubuntu V=2 reaches a point where it produces the following error during linking:

``` 
LD build/release-linux-x86_64/ioq3ded.x86_64
build/release-linux-x86_64/ded/sys_main.o: In function `main':
sys_main.c:(.text.startup+0xe): undefined reference to `bcm_host_init'
collect2: error: ld returned 1 exit status
```
My impression is that bcm_host_init should be guarded here.

**Comment by sebastianene07** [comment]
I have a working patch for Ubuntu 18.04 X86_64 should I make a PR ?

**Comment by popcornmix** [comment]
So you are trying to build raspberrypi/quake3 to run on an x86_64 Ubuntu host?

If you have a patch that fixes that without breaking the ability to build for raspberry pi then sure, submit a PR.

**Comment by sebastianene07** [comment]
Correct I am trying to build on X86_64 Ubuntu host. Currently the patch will break the raspberry pi compilation but I'll fix this in a new commit and then I'll post a PR.
My branch is https://github.com/SebiEne/quake3/tree/sene/quake3_fix_x86_compilation_ubuntu
